master:
  script:
    - apt-get update -qy
    - apt-get install -qy python-numpy
    - pwd
    - echo $HOME
    - echo $PWD
    - echo $PYTHONPATH
    - PATH=$PATH:$PWD/tools PYTHONPATH=$PYTHONPATH:$PWD python setup.py test
    - PYTHONPATH=$PYTHONPATH:$PWD python ase/utils/geometry.py
